apiVersion: v1
kind: Pod
metadata:
  name: tryproject
  labels:
    label1: label1
spec:
  containers:
    - image: somiasrour/project
      name: tryproj
      imagePullPolicy: IfNotPresent
      name: tryproject
      ports:
        - containerPort: 80